### ISSUE TITLE
That Ruby Code of Conduct In Full

### ISSUE THREAD

**Issue by hnrysmth** [hnrysmth/words#1]
So [the Ruby project has adopted a Code of Conduct](https://www.ruby-lang.org/en/conduct/). Good news, right? Well, it would be if the document was based on any real-world understanding of harassment and abuse. In its current form, it does more harm than good.

I need to be writing a CV and applying for jobs right now but I'm gonna throw some time at explaining all the problems I can see. Let's start at the beginning.

> We have picked the following code of conduct based on PostgreSQL CoC, for
> Ruby developer’s community for safe, productive collaboration. Each Ruby 
> related community (conference etc.) may pick their own CoC.

Right off the bat this document reflects its author's shallow knowledge of the problem domain. The first sentence incorrectly states that it's based on the Postgres project's Code of Conduct. What this refers to is, in fact, a draft proposal from the Postgres mailing list that [has not been officially adopted](http://www.postgresql.org/message-id/56A8516B.8000105@agliodbs.com).

That Postgres draft has a troubled history. It originated as an attempt to ward off "Social Justice Warriors", with the [first iteration](http://postgresql.nabble.com/WIP-CoC-td5881640.html) even going as far as including a sixth rule stating that "The CoC is not about Social Justice". It was originally so overtly keen to discourage people from reporting abuse that the second rule went on about how "the offended individual is more interested in being a victim than moving forward". The language was gradually softened with each iteration but the overall structure and intent of the document has remained the same. It is a poor choice by any actually useful standard of measurement.

The other major fuckup in this first paragraph is the explicit descoping of conduct at conferences. This actually makes things worse. Before, if a Ruby contributor got drunk and assaulted someone at a conference there was at least the *possibility* of consequences within the project. That is now officially off the table. It's open season.

> This document provides community guidelines for a safe, respectful, productive,
> and collaborative place for any person who is willing to contribute to the Ruby
> community. It applies to all “collaborative space”, which is defined as
> community communications channels (such as mailing lists, submitted patches,
> commit comments, etc.).

More explicit descoping of conferences, just in case it wasn't completely clear already. This Code of Conduct *reeeeally* goes out of its way to rule out acting on bad things that might happen at conferences. Gotta wonder what's being brushed under the carpet here.

> Participants will be tolerant of opposing views.

Let's be clear. This means that if somebody on the Ruby project wants to talk publicly about their hatred for people of your race, gender, or sexuality, then you will be expected to meekly submit to this and continue providing your labour without complaint.

Rule one of this Code of Conduct is basically "STFU we don't care if racist behaviour among our contributors keeps people of colour from getting involved."

> Participants must ensure that their language and actions are free of personal
> attacks and disparaging personal remarks.

Personal attacks are bad. Disparaging personal remarks are bad. Neither of these are allowed. Congratulations, Ruby project, you have adopted one explicit rule against the simplest, easiest, lowest effort type of community misconduct.

> When interpreting the words and actions of others, participants should always
> assume good intentions.

This is really just a reinforcement of the first rule. Mostly it just serves to discourage reporting misconduct. It says "If you saw rule 1 and for some reason still insist on asking us for help we will drag our feet *SO* much you'll regret bothering."

> Behaviour which can be reasonably considered harassment will not be tolerated.

Why not just say "Harassment will not be tolerated" here? Let's all have a little think about what extra meaning is conveyed by the qualifier, "behaviour which can be reasonably considered...". It's almost like it was written by somebody who thinks Codes of Conduct are SJW bullshit and it's trying to pre-emptively cast doubt on every possible future attempt to actually report harassment.

So yeah this is a bloody terrible Code of Conduct and the harm isn't confined to the Ruby project. The entire Open Source community is watching. The adoption of this CoC by Ruby will be seen as legitimising it. Other projects are likely to follow. We're all worse off because of this and I'm so fucking disappointed.

**Comment by hnrysmth** [comment]
Those are just the problems with what little it *does* say. There's a whole other discussion to be had about the glaring omission of enforcement details. The Contributor Covenant, for example, provides an email contact and promises confidentiality. The Ruby Code of Conduct makes no meaningful provisions for what to do when somebody actually violates it. It's like omitting proper error handling out of sheer optimism and wilful ignorance.

```ruby
begin
  participants.be_tolerant_of_opposing_views!
  participants.disable_personal_attacks!
  participants.disable_disparaging_remarks!
  participants.assume_good_intentions! # lol intent is magic
  participants.disable_harassment!
rescue
  # ¯\_(ツ)_/¯ idk lol
  puts "MINASWAN"
end
```

**Comment by CartesianDuelist** [comment]
Yeah it's too bad there's not some other code of conduct like the law that covers assault at a conference. Also, you're patently wrong:

"The other major fuckup in this first paragraph is the explicit descoping of conduct at conferences. "

Let's take a look at the text:

"It applies to all “collaborative space”, which is defined as community communications channels (such as mailing lists, submitted patches, commit comments, etc.)."

You don't think conferences are a collaborative space?

**Comment by jacobsmith** [comment]
First, I completely agree that the Ruby CoC should be revamped and extended to include conferences (perhaps to gain a "Official Ruby Conference" tag, or something of the like). 

Just to play devil's advocate @CartesianDuelist about the conferences being "collaborative spaces", they specifically go out of their way to explicitly define that as "community communications channels". While obviously communication occurs at conferences, I think it could be argued that they are not "community communication channels" as they are:
  1. Exclusive based on geography (you have to be there to be in the conversation), while the others are asynchronous, available on the open Internet, and public in nature.
  2. I don't think that conferences are a "channel" of communication.

To be clear, I think that the CoC has *much* room for improvement, I only want to point out how I think they are excluding conferences from falling under the CoC umbrella.

**Comment by CartesianDuelist** [comment]
The CoC is perfect in that it doesn't enable secret tribunals and outgrouping to get rid of persona-non-grata and simulatenously create a caste of untouchables, which is what the vast majority of them do. One only has to look at the twitter of the Contributor's Covenant to see that her own CoC doesn't apply to her. 

That said, let's say someone assaults someone at a conference. If they are merely accused of it, do they get kicked out because of a "Believe the Victims" doctrine? Do we wait for a conviction? Well, the law took care of that for us, now.

**Comment by hnrysmth** [comment]
The confidentiality guarantee is important. Without a structured way of confidentially reporting misconduct you end up with victims being publicly dragged through the mud in retaliation for speaking out. It is a [real thing that actually happens](http://geekfeminism.wikia.com/wiki/Noirin_Shirley_ApacheCon_incident). It is not some terrifying conspiracy against white men. It is a pragmatic solution to a real problem.

**Comment by CartesianDuelist** [comment]
Forgive me if I don't expect impartiality from "Geek Feminism". 

As for the confidentiality guarantee, you in this situation enable abusers to manipulate the system in a similar way. We have channels for this. They are called "the police". 

Additionally this was the same Ada Initiative that pushed to non-platform people and puritanically police conferences, e.g. removing Violet Blue from a speaking position because her talk would supposedly enable predatory behaviour. 

' It is not some terrifying conspiracy against white men"

How very inclusive of you.

**Comment by hnrysmth** [comment]
If you sexually assaulted a colleague at an event hosted by your employer, you would lose your job. Your employer would not force your victim to continue working side-by-side with you until they secured a conviction against you. It is a normal everyday thing for organisations to impose their own standards of conduct and consequences for misconduct that operate outside the legal system. If you punch the coach of your amateur football team, you will no longer be allowed to participate there. This is how the real world works and extending these practices to Open Source communities is not a fascist power grab.

**Comment by CartesianDuelist** [comment]
Unlike a job, however, Open Source communities are not bound by tort law or employment law to prevent such abuses from occurring, nor are actual vocations open up to the anonymous attacks and no-platforming that the Open Source community is. 

Do you believe that someone, if accused of harassment, should be permanently barred from the Ruby community and the word of the victim alone?

**Comment by hnrysmth** [comment]
It's pretty reasonable IMO to expect a thorough internal investigation before any severe consequences are applied.

**Comment by CartesianDuelist** [comment]
And does Ruby have these? Are we going to ensure that the investigation process is fair and open? Are those on it going to be trained in mediation techniques? Civil law? Criminal? 

You're aware that I could, under most vocations' anti-harassment policies *right now*, reasonably claim harassment and toxic work environment for your little 'white men' comment on several bases?

Are you beginning to see the issues in what you're proscribing, yet?

**Comment by hnrysmth** [comment]
No, they're obviously however good at conflict resolution as they happen to be. The point is they should at least commit to doing their best. People shouldn't have to choose between the career hit of leaving an open source project or the mental health hit of continuing to collaborate with toxic people. We should at least *aim* higher than that.

**Comment by CartesianDuelist** [comment]
"No, they're obviously however good at conflict resolution as they happen to be. "

Are they? I can name several people who have been effectively no-platformed for being 'toxic' on their own twitter profiles.

**Comment by dpyro** [comment]
What incidents of harassment have occurred in the Ruby community that merits a CoC?

**Comment by Jogyn** [comment]
Ok that's it I'm done with putting up with this crap.

> Right off the bat this document reflects its author's shallow knowledge of the problem domain. 

No such behavior was ever presented in the main thread as to why this was necessary to begin with. No examples cited, no hint as to why a CoC was ever necessary. It was and is not reasonable to expect the community to be SJW anti-harasssment activists like you are. You are clearly a politically correct conduct pusher,  you should just come out and own up to it. Take off the mask so we know who we are talking to. Your text groans with sjw.

> if a Ruby contributor got drunk and assaulted someone at a conference there was at least the possibility of consequences within the project. That is now officially off the table. It's open season.

complete fantasy, delusion. The consequences would be extreme. The person would likely go to jail and have their reputation destroyed at the same time. There is a punishment doled out for that kind of action and it's not the Ruby communities job to do it. The social consequences are that the person would probably become a pariah and would not show up again out of pure embarassment to ANY software community. Ruby is not the police, and nor should they be. 

> This Code of Conduct reeeeally goes out of its way to rule out acting on bad things that might happen at conferences. Gotta wonder what's being brushed under the carpet here.

Again delusion. There is a code of conduct everywhere you go it's called the LAW. You seem to want to pin a sherrifs badge on the Ruby community so bad. Wonder why that is? Are you pushing a social justice agenda perhaps?

> Let's be clear. This means that if somebody on the Ruby project wants to talk publicly about their hatred for people of your race, gender, or sexuality, then you will be expected to meekly submit to this and continue providing your labour without complaint.

Bullshit this would be classified as a personal attack and perhaps harassment as well depending on the comment's seriousness. You are using the most made up and unlikely and to date, probably non existent examples to appeal to peoples emotions, but you aren't actually making a substantive argument. You have to use examples that are likely to occur. All of your examples are made up as it relates to the Ruby communities history. You are literally making up bullshit hypotheticals and want the community to build an orwellian document based your pure manufactured overly extreme examples. Post the example from the Ruby community that has occured in the past of someone doing anything even closed to what you mentioned. Post it. I'll wait. 

> This is really just a reinforcement of the first rule. Mostly it just serves to discourage reporting misconduct. It says "If you saw rule 1 and for some reason still insist on asking us for help we will drag our feet SO much you'll regret bothering."

Again bullshit, it means thats you have to have a thick skin, if you are a victim complex person such as yourself it means, grow up, the internet has no tone, so assume good will until it is proven otherwise. Same as we all do in all of our day to day interactions. Take responsibility for yourself, no ones going to coddle you. 

> Why not just say "Harassment will not be tolerated" here? Let's all have a little think about what extra meaning is conveyed by the qualifier, "behaviour which can be reasonably considered...". 

Because the sjw is not reasonable and they don't know what harassment is. Therefore you need the reasonable qualifier in there as no doubt you will be dealing with problem sjw's most when it comes to this CoC. In really blatant terms, and I don't know how I can make this more clear. It means "ACTUAL HARASSMENT" not what sjw's think harassment is. Harassment is prolonged verbal abuse over an extended measure of time that offends or humiliates a person. Not someone making an offhand comment and an sjw getting immediately butthurt with someone disagreeing with them.
This part tells the sjw and everyone else that if you get butthurt over disagreement that you have not necessarily been "harassed" 

This code of conduct goes much further than I would have. I would tear it down and put up the code of merit. It's really shameful that you are using the good will of the open source community to push a feminist sjw agenda onto them. You should be ashamed of yourself, it's disgraceful and infantile.

**Comment by hnrysmth** [comment]
Here's a picture of a Pomeranian. It's a type of dog.

![pomeranian_orange-sable_coco](https://cloud.githubusercontent.com/assets/566159/13139645/73d7c23c-d625-11e5-8071-6fe421b77594.jpg)

There are people who breed and show these cute little doggies. Those people usually organise into a local club which runs dog shows and other things. Here's an excerpt from [the Scottish Pomeranian Club](http://www.scottishpomeranian.co.uk/p/club-history.html)'s rules.

> If the conduct of any member shall, in the opinion of the Committee of the Club, be injurious to or likely to be injurious to the character or interests of the Club, the Committee of the Club may, at a meeting the notice convening which includes as an object the consideration of the conduct of the member, determine that a Special General Meeting of the Club shall be called for the purpose of passing a resolution to expel him. Notice of the Special General Meeting of the Club shall be sent to the accused member giving particulars of the complaint and advising the place, the date, and the hour of the meeting that he may attend and offer an explanation. If at the Meeting a resolution is passed by a two-thirds majority of members present and voting, his name shall be erased from the list of members, and he shall cease for all purposes to be a member of the Club except that he may within two calendar months from the date of such a meeting appeal to the Kennel Club upon and subject to such conditions as the Kennel Club may impose.

That's the Official Very Serious Rules for expelling people from the Cute Little Doggie Club. It is a very normal, mundane, boring, everyday thing for organisations to have their own rules about conduct.

**Comment by rgladwell** [comment]
Good summary, the Ruby pseudo-CoC is so passive-aggressive and bad faith it makes the mind boggle. It sends out a clear message: minorities need not apply!

> Are you pushing a social justice agenda perhaps?

Like you don't have your own, privileged agenda that can be seen from space.

**Comment by CartesianDuelist** [comment]
Saying someone has a 'privileged' agenda doesn't mean anything: do you believe that the CoC explicitly bars minorities from contributing their code? Do you believe that the Ruby community is simply a cesspit of racial slurs and exclusionary behavior? Do you think it must be explicitly mentioned that the project looks down on racism/sexism and so on because of this endemic problem in the Ruby community? 

Also given that Matz is a Japanese man, a racial minority. Do you believe he simply needs to be told what his best interests are? 

"That's the Official Very Serious Rules for expelling people from the Cute Little Doggie Club. It is a very normal, mundane, boring, everyday thing for organisations to have their own rules about conduct."

Oh for sure, and Ruby has one! It's just one you don't like.

**Comment by rgladwell** [comment]
You've said it yourself: the psuedo-CoC doesn't *explicitly* ban minorities, it just implicitly skews things in the favour of the straight, white, males. *That* is what privilege means.

**Comment by CartesianDuelist** [comment]
Oh, does it now?  By what mechanism? You're saying a lot of things without justification, here. 

Again, do you believe racism and sexism to be an endemic enough problem in the Ruby community that those who would be its ostensible victims need be explicitly told that they won't be tolerated? 

Be specific, now--and in your own words.

**Comment by rgladwell** [comment]
I think @hnrysmth and others have made ample arguments about exactly how the pseudo-CoC is insufficient and works purely in the favour of the privileged. Feel free to come off anon, and we can talk about it further, @CartesianDuelist ;)

**Comment by CartesianDuelist** [comment]
Nope, I want your arguments out in the open. @hnrysmth  is wrong about quite a few things that I've already laid out, for example:


"Behaviour which can be reasonably considered harassment will not be tolerated."

This is pretty much the CoC of every business I have ever worked at. What this means is that claiming on your own twitter account the most heinous political opinions ever doesn't reasonably count as harassment, but spouting them--especially at a person--does. 

More than anything, I've seen that the progenitors and adherents to various CoC have no issues about continually disparaging the 'privileged' however they see fit in ways that, if directed at the 'unprivileged', would get them immediately removed from the project. That is what many people have issues with--creating a caste of untouchables who can abuse the system with impunity.

**Comment by rgladwell** [comment]
If Henry "is wrong about quite a few things" why are you hiding behind a fake, anonymous account?

> 've seen that the progenitors and adherents to various CoC have no issues about continually disparaging the 'privileged' however they see fit in ways that,

Hmmm you've just completely made that up.

**Comment by CartesianDuelist** [comment]
"If Henry "is wrong about quite a few things" why are you hiding behind a fake, anonymous account?"

Ah yes, the 'if you have nothing to hide you have nothing to fear' canard. Good one. Not linking my private identity to opinions that, however reasonable they may or may not be, will then make me a persona-non-grata like I have stated above is in my best interest. I have seen far too many friends have their employers be called based on these types of disucssions. 

"Hmmm you've just completely made that up."

Calling someone a "dudebro" is, by any reasonable person's measure, sexist, and no, you don't get to frame the word in a peurile "BUT BUT POWER PLUS PREJUDICE" manner.

**Comment by rgladwell** [comment]
I'm super confused: if the pseudo-CoC is "reasonable" you should have no problem being associated with your opinions? After all, we're not the NSA or FBI, dude?

Or (more likely) you're anonymous because no amount of reasonable debate with you will actually make any difference to your prejudices and you're just looking to harass and bully Henry without any blowback for yourself.

>  in a peurile "BUT BUT

After all, if you were really serious about discussing this you wouldn't be so condescending.

> Calling someone a "dudebro" is, by any reasonable person's measure, sexist

Nope.

You are not a reasonable person either.

**Comment by CartesianDuelist** [comment]
"I'm super confused: if the pseudo-CoC is "reasonable" you should have no problem being associated with your opinions? After all, we're not the NSA or FBI?"

Oh fuck off. Opinons, no matter how reasonable, can be used against you in various realms if they do not align with the status quo. 

"Nope."

A masterful retort. Sorry, using two male-directed slang at someone disparagingly is sexist. If I called someone a "Chick-gal" regarding how, say, unreasonable I found them, you'd be calling me a sexist.

**Comment by rgladwell** [comment]
Ha ha ha you say "A masterful retort" after you say "Oh fuck off"... indeed, you are the master of discourse.

You're clearly not interested in discussion, only in shouting down dissent, bullying those who disagree with you, cowering behind your anonymity..

...and...

...getting the last word... ;)

...wait for it...

**Comment by CartesianDuelist** [comment]
Oh, I will take it. 

You do not get to use my "anonymity" to paint me as a coward--me being afraid and concerned about being painted as a 'bully'--where, by the way?--and all that comes from that does not make me wrong, it makes me aware of the implicit threats of being accused by _people like you_ of being a 'harasser' and the effects that will have on my livelihood. 

Using 'oh fuck off" as proof I am not interested in discourse when all you've mustered up is accusations that I am 'cowering' behind anonymity--afraid that the true 'bullies' will do things I couldn't dream of doing to another person that they seem to do with glee--is as intellectually dishonest and transparent as it can get.

**Comment by rgladwell** [comment]
...there we go

That was a long one.

OK, attention time is over, consider yourself spanked.

**Comment by CartesianDuelist** [comment]
Ah yes, how empathetic and constructive. Truly a beacon of social justice you are.

**Comment by hnrysmth** [comment]
I'm going to no-platform us all now. This has been cool. @CartesianDuelist, thanks at least for being a sounding board that's helped me put some extra thoughts into writing. We disagree, but have a cool day anyway. Appreciate the support @rgladwell :smile:
